### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by droxey** [Jeromeschmidt/contractorProject#1]
**CRUD + Resource Association:** 3
**Documentation:** 2 (Add specific and in-depth docstrings for your project, more info in README)
**Test Coverage:** 2 (Add more CRUD related tests to level up)
**Templates:** 3
**Heroku:** 3
**Git Commits:** 4

Great job!

**Comment by Jeromeschmidt** [comment]
Thanks for the awesome feedback @droxey, I'll be sure to make some changes to level up the project!
